import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const robotoFont = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SAV Caustier",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={robotoFont.variable}>
      <body className={robotoFont.className}>{children}</body>
    </html>
  );
}
